services:
  #sets up how to make the source data available
  demo:
  tms:
    origin: 'nw'
  wms:
    #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.
    srs: ['EPSG:900913','EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
      contact:
        person: Your Name
        position: Technical Director
        organization: Some Company
        address: Long street
        city: Timbuktu
        postcode: 123456AD
        country: South Pole
        email: info@example.com
      access_constraints:
        This service is intended for private and evaluation use only.
        The data is licensed as Creative Commons Attribution-Share Alike 2.0
        (http://creativecommons.org/licenses/by-sa/2.0/)
      fees: 'None'

layers:
  - name: osm_bright
    title: Open Map Tiles in OSM Bright Style
    sources: [osm_bright_cache]
  - name: klokantech
    title: Open Map Tiles in Klokantech Style
    sources: [klokantech_cache]
  - name: dark_matter
    title: Open Map Tiles in Dark Matter Style
    sources: [dark_matter_cache]
  - name: fiord_color
    title: Open Map Tiles in Fiord Color Style
    sources: [fiord_color_cache]
  - name: positron
    title: Open Map Tiles in Positron Style
    sources: [positron_cache]
    
caches:
  #setup the cache for the open streetmap tiles. This cache is used by the layer above.
  osm_bright_cache:
    sources: [osm_bright_tiles]
    format: image/png
    grids: [osm_grid]
  klokantech_cache:
    sources: [klokantech_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
    grids: [osm_grid]
  dark_matter_cache:
    sources: [dark_matter_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
    grids: [osm_grid]
  fiord_color_cache:
    sources: [fiord_color_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
    grids: [osm_grid]
  positron_cache:
    sources: [positron_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
    grids: [osm_grid]
  
sources:
   osm_bright_tiles:
     type: tile
     url: 'http://PROXY_HOST_TILESERVER:8080/styles/osm-bright/%(tms_path)s@2x.%(format)s'
     grid: osm_grid #the grid to use for the osm tiles. This is really important. It is specified below.
   klokantech_tiles:
     type: tile
     url: 'http://PROXY_HOST_TILESERVER:8080/styles/klokantech-basic/%(tms_path)s@2x.%(format)s'
     grid: osm_grid #the grid to use for the osm tiles. This is really important. It is specified below.
   dark_matter_tiles:
     type: tile
     url: 'http://PROXY_HOST_TILESERVER:8080/styles/dark_matter/%(tms_path)s@2x.%(format)s'
     grid: osm_grid #the grid to use for the osm tiles. This is really important. It is specified below.
   fiord_color_tiles:
     type: tile
     url: 'http://PROXY_HOST_TILESERVER:8080/styles/fiord-color/%(tms_path)s@2x.%(format)s'
     grid: osm_grid #the grid to use for the osm tiles. This is really important. It is specified below.
   positron_tiles:
     type: tile
     url: 'http://PROXY_HOST_TILESERVER:8080/styles/positron/%(tms_path)s@2x.%(format)s'
     grid: osm_grid #the grid to use for the osm tiles. This is really important. It is specified below.


grids:
  osm_grid:
    #this srs and origin specify a grid that can be used elsewhere in the configuration. In this example it is used for the osm_tiles source. These settings are correct for openstreetmap.org tiles.
    #The google mercator srs is used (also called EPSG:900913), and the origin of the tiles is north-west). If you get this wrong, you might very well get an all-blue world.
    srs: EPSG:900913
    origin: nw

globals:
  #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.
  cache:
    # where to store the cached images
    base_dir: '/cache'
    # where to store lockfiles
    lock_dir: './cache/locks'


  # image/transformation options
  image:
      resampling_method: bilinear
      jpeg_quality: 90
